name: R_Data-Corrector
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.10.0=py311haa95532_0
  - arch-py=8.0.0=py311h17033d2_0
  - argon2-cffi=25.1.0=py311haa95532_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - babel=2.17.0=py311haa95532_0
  - beautifulsoup4=4.14.2=py311haa95532_0
  - bleach=6.3.0=py311haa95532_0
  - blinker=1.9.0=pyhff2d567_0
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=h32ff316_0
  - dash=2.17.1=pyhd8ed1ab_0
  - dash-ag-grid=2.4.0=pyhd8ed1ab_0
  - dash-bootstrap-components=1.5.0=pyhd8ed1ab_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fmt=12.0.0=h29169d4_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - h11=0.16.0=py311haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_1
  - jupyter_server=2.17.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.5.0=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h5f2f476_6_cuda
  - libarrow-acero=22.0.0=h7d8d6a5_6_cuda
  - libarrow-compute=22.0.0=h2db994a_6_cuda
  - libarrow-dataset=22.0.0=h7d8d6a5_6_cuda
  - libarrow-substrait=22.0.0=hf865cc0_6_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudnn-dev=9.10.2.21=hca898b4_0
  - libcudss=0.7.1.4=hca898b4_0
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcurl=8.17.0=h43ecb02_1
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libmagma=2.9.0=hb6a17ea_3
  - libnvjitlink=12.9.86=hac47afa_2
  - libparquet=22.0.0=h7051d1f_6_cuda
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=h83e8143_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtorch=2.9.1=cuda128_mkl_hbf96477_300
  - libutf8proc=2.11.2=hb980946_0
  - libuv=1.51.0=hfd05255_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.46.0=py311h4f568be_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2025.3.0=hac47afa_454
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.6.1=pyhcf101f3_0
  - notebook=7.5.0=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numba=0.63.1=py311h34437f8_0
  - numpy=2.3.5=py311h80b3fa1_0
  - openssl=3.6.0=h725018a_0
  - optree=0.18.0=py311h3fd045d_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h11fd7f3_2
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - patsy=1.0.2=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py311haa95532_0
  - plotly=5.17.0=pyhd8ed1ab_0
  - polars=1.36.1=pyh6a1acc5_0
  - polars-runtime-32=1.36.1=py310hca7251b_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pyarrow=22.0.0=py311h1ea47a8_0
  - pyarrow-core=22.0.0=py311h819ed09_0_cuda
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python-json-logger=4.0.0=py311haa95532_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.9.1=cuda128_mkl_py311_h7c65ee9_300
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - retrying=1.4.2=pyhe01879c_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - scikit-learn=1.8.0=np2py311hd01f973_1
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - statsmodels=0.14.6=py311h17033d2_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=py311haa95532_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h02ab6af_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.1=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - scipy==1.16.3
prefix: C:\Users\Carlos\anaconda3\envs\R_Data-Corrector
